'use strict';
function loan(principal,rate,months){const r=rate/1200;const payment=r===0?principal/months:principal*r/(-Math.expm1(-months*Math.log1p(r)));let balance=principal,total=0;const balances=[principal],payments=[];for(let i=0;i<months;i++){const interest=balance*r;const paid=i===months-1?balance+interest:Math.min(payment,balance+interest);balance=Math.max(0,balance+interest-paid);total+=paid;payments.push(paid);balances.push(balance);}return {payment,total,interest:total-principal,balances,payments,months};}
function steppedLoan(principal,rate,months,firstMonths,afterRate){if(!firstMonths||firstMonths>=months||afterRate===rate)return loan(principal,rate,months);const original=loan(principal,rate,months);const balance=original.balances[firstMonths],rest=loan(balance,afterRate,months-firstMonths);const firstPaid=original.payments.slice(0,firstMonths);const total=firstPaid.reduce((sum,p)=>sum+p,0)+rest.total;return {payment:original.payment,afterPayment:rest.payment,total,interest:total-principal,balances:original.balances.slice(0,firstMonths).concat(rest.balances),payments:firstPaid.concat(rest.payments),months};}
function calculate(v){const fees=v.fees*10000;const current=loan(v.balance*10000,v.currentRate,v.currentYears*12);const next=steppedLoan(v.balance*10000+(v.financeFees?fees:0),v.newRate,v.newYears*12,v.fixedMonths,v.afterRate);const upfront=v.financeFees?0:fees;const saving=current.total-next.total-upfront;let cumulative=-upfront;const cash=[cumulative];for(let i=0;i<Math.max(current.months,next.months);i++){cumulative+=(current.payments[i]||0)-(next.payments[i]||0);cash.push(cumulative);}let recovery=null;if(saving>0){let suffix=Infinity;for(let i=cash.length-1;i>=1;i--){suffix=Math.min(suffix,cash[i]);if(suffix>=-0.001)recovery=i;}}return {current,next,saving,recovery,upfront,fees};}
if(typeof module!=='undefined')module.exports={loan,steppedLoan,calculate};
if(typeof document!=='undefined'){
const form=document.getElementById('form'),yen=x=>Math.round(x).toLocaleString('ja-JP')+' 円',man=x=>(Math.abs(x)/10000).toLocaleString('ja-JP',{minimumFractionDigits:1,maximumFractionDigits:1});
function render(){const error=document.getElementById('error');const customError=bankValidation();if(!form.checkValidity()||customError){error.hidden=false;error.textContent=customError||(selectedPlan()?'保証料・その他費用の見積額を入力し、金額・金利・期間の入力範囲を確認してください。不要な費用は0を入力できます。':'金額・金利・期間を入力範囲内で指定してください。期間は1〜50年の整数です。');document.querySelector('.results').hidden=true;return;}error.hidden=true;document.querySelector('.results').hidden=false;const v={};for(const id of ['balance','currentRate','currentYears','newRate','newYears','fees'])v[id]=Number(document.getElementById(id).value);v.financeFees=document.getElementById('financeFees').checked;const plan=selectedPlan();if(plan?.type==='initial'){v.fixedMonths=plan.years*12;v.afterRate=Number(el('afterRate').value);}const {current:a,next:b,saving,recovery,upfront}=calculate(v);document.getElementById('saving').innerHTML=man(saving)+'<small>万円'+(saving<-.01?' 増加':saving>.01?' 節約':'')+'</small>';document.getElementById('verdict').textContent=saving<-.01?'総支払額が増加':saving>.01?'借り換えで節約':'総支払額は同じ';document.getElementById('savingNote').textContent=v.financeFees?'諸費用とその利息を、新しいローンの支払いに含めています。':'借り換え費用 '+yen(upfront)+' を差し引いた金額です。';const difference=a.payment-b.payment;document.getElementById('monthlySaving').textContent=yen(Math.abs(difference))+(difference<-.01?' 増':difference>.01?' 減':'');document.getElementById('breakEven').textContent=recovery===null?'回収できません':v.financeFees?'初月から':`${Math.floor(recovery/12)?Math.floor(recovery/12)+'年 ':''}${recovery%12?recovery%12+'か月':''}`||'0か月';const rows=[['毎月の返済額（当初）',yen(a.payment),yen(b.payment)],['返済期間',v.currentYears+' 年',v.newYears+' 年'],['支払う利息',yen(a.interest),yen(b.interest)],['諸費用（現金払い）',yen(0),yen(upfront)],['総支払額',yen(a.total),yen(b.total+upfront)]];if(b.afterPayment)rows.splice(1,0,['固定期間終了後の月額','—',yen(b.afterPayment)]);document.getElementById('comparison').innerHTML=rows.map(r=>`<tr><th scope="row">${r[0]}</th><td>${r[1]}</td><td>${r[2]}</td></tr>`).join('');chart(a,b);}
function chart(a,b){const W=600,H=210,L=57,R=15,T=15,B=35,n=Math.max(a.months,b.months),max=Math.max(a.balances[0],b.balances[0]);const x=m=>L+m/n*(W-L-R),y=v=>T+(1-v/max)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="現在と借り換え後のローン残高。完済時に残高がゼロになる推移。">`;for(let i=0;i<=3;i++){let val=max*i/3;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(val)}" y2="${y(val)}" stroke="#e9eef5"/><text x="${L-8}" y="${y(val)+4}" text-anchor="end">${Math.round(val/10000).toLocaleString()}万</text>`;}for(let i=0;i<=4;i++)svg+=`<text x="${x(n*i/4)}" y="${H-10}" text-anchor="middle">${+(n*i/4/12).toFixed(1)}年</text>`;for(const [l,c]of [[a,'#9aaac1'],[b,'#2c7be6']]){const points=[];for(let i=0;i<=n;i+=1)points.push(`${x(i).toFixed(2)},${y(l.balances[i]||0).toFixed(2)}`);svg+=`<polyline fill="none" stroke="${c}" stroke-width="3" stroke-linejoin="round" points="${points.join(' ')}"/>`;}document.getElementById('chart').innerHTML=svg+'</svg>';}
form.addEventListener('input',render);form.addEventListener('submit',e=>e.preventDefault());document.getElementById('reset').addEventListener('click',()=>{form.reset();configureBank(false);el('guaranteeCost').readOnly=false;el('guaranteeCost').dataset.zero='false';render();});render();}
