'use strict';
const el=id=>document.getElementById(id);
function selectedPlan(){const bank=BANKS[el('bank').value];return bank?bank.plans[Number(el('bankPlan').value)]:null;}
function configureBank(resetRate=true){const bank=BANKS[el('bank').value],active=!!bank;el('bankControls').hidden=!active;el('bankFees').hidden=!active;el('fees').readOnly=active;el('feesHint').textContent=active?'公表手数料と入力した追加費用の合計（自動計算）':'事務手数料・登記費用・保証料・繰上返済手数料などの合計';for(const id of ['guaranteeCost','otherCosts']){el(id).disabled=!active;el(id).required=active;}if(!active){el('afterControls').hidden=true;el('afterRate').disabled=true;return;}const p=selectedPlan();el('rateChoice').innerHTML=p.rates.map((r,i)=>`<option value="${r}">${r.toFixed(3).replace(/0+$/,'').replace(/\.$/,'')}%${p.rates.length>1?(i===0?'（公表範囲の下限）':'（公表範囲の上限）'):''}</option>`).join('');if(resetRate){el('newRate').value=p.rates[0];el('afterRate').value=p.rates[0];}el('afterControls').hidden=p.type!=='initial';el('afterRate').disabled=p.type!=='initial';el('afterRate').required=p.type==='initial';el('bankRateNote').textContent=(p.type==='initial'?`当初${p.years}年間の金利。終了後は下の想定金利で試算。`:p.type==='variable'?'変動金利が今後も一定と仮定した試算です。':'全期間固定金利。')+' 下限・優遇金利の適用は保証されません。借り換え後の金利は見積もりに合わせて直接変更できます。';el('bankNotes').textContent=bank.notes;el('bankSources').innerHTML=bank.sources.map(([label,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer">${label}</a>`).join('');el('bankDate').textContent=`公式情報確認日：${bank.date} ／ 自動更新はありません`;el('guaranteeCost').readOnly=!!p.guaranteeZero;if(p.guaranteeZero)el('guaranteeCost').value=0;else if(el('guaranteeCost').dataset.zero==='true')el('guaranteeCost').value='';el('guaranteeCost').dataset.zero=String(!!p.guaranteeZero);el('guaranteeNote').textContent=p.guaranteeZero?'新規利用の保証料はろうきん負担（公式商品概要）。追加の保証関連費用は不要として計算します。':'審査・期間で金額が変わるため見積額を入力してください。JAの一律保証料30,000円は自動計算に含まれています。分割・金利上乗せを選ぶ場合はここに0を入力し、見積もりの上乗せ分を借り換え後の金利（固定終了後も）に加えてください。';if(el('bank').value!=='ja'&&!p.guaranteeZero)el('guaranteeNote').textContent='審査・期間で金額が変わるため見積額を入力してください。分割・金利上乗せの場合は0を入力し、見積もりの上乗せ分を借り換え後の金利（固定終了後も）に加えてください。';syncBankCosts();}
function syncBankCosts(){const p=selectedPlan();if(!p)return;const principal=Number(el('balance').value)*10000,extra=(Number(el('guaranteeCost').value)+Number(el('otherCosts').value))*10000;const fees=bankCosts(principal,p,extra,el('financeFees').checked);el('fees').value=(fees/10000).toFixed(8);const financed=el('financeFees').checked?principal+fees:principal;const fee=p.fixed+p.percent*financed+(p.electronicTier?electronicFee(financed):0);el('feeBreakdown').textContent=`公表手数料等：${Math.round(fee).toLocaleString('ja-JP')}円 ＋ 追加見積額：${Math.round(extra).toLocaleString('ja-JP')}円`+(el('guaranteeCost').value===''||el('otherCosts').value===''?'（見積額の入力待ち）':'');}
function bankValidation(){const b=BANKS[el('bank').value];if(!b)return '';const years=Number(el('newYears').value),amount=Number(el('balance').value)+(el('financeFees').checked?Number(el('fees').value):0);if(years<b.minYears||years>b.maxYears)return `${b.name}の登録商品の返済期間は${b.minYears}〜${b.maxYears}年です。`;if(b.remainingLimit&&years>Number(el('currentYears').value))return 'JA借換応援型は現在のローンの残り期間以内です。';if(amount<b.minAmount||amount>b.maxAmount)return `${b.name}の登録商品の借入額の範囲は${b.minAmount.toLocaleString()}〜${b.maxAmount.toLocaleString()}万円です。`;return '';}
el('bank').addEventListener('change',()=>{const b=BANKS[el('bank').value];if(b){el('bankPlan').innerHTML=b.plans.map((p,i)=>`<option value="${i}">${p.name}</option>`).join('');}configureBank();if(!b)el('fees').value=70;el('form').dispatchEvent(new Event('input'));});
el('bankPlan').addEventListener('change',()=>{configureBank();el('form').dispatchEvent(new Event('input'));});
el('rateChoice').addEventListener('change',()=>{el('newRate').value=el('rateChoice').value;el('form').dispatchEvent(new Event('input'));});
el('form').addEventListener('input',syncBankCosts);configureBank(false);
